### ISSUE TITLE
Improve CI with static code analysis and unit tests

### ISSUE THREAD

**Issue by jmadden173** [jlab-sensing/soil-power-sensor-firmware#59]
**Describe the Enhancement**
Using platformio remote development feature, run our unit tests on actual hardware. The soil power sensor will be connected to an external computer, most likely raspi, through a debugger.

**Benefits**

- Ability to check simple code changes without having someone else flash a device.
- Static code analysis will prevent common errors (ie. array index out of range)
- Improve code quality
- Outside developers can check their code. For example, PR #56 , is from a perspective GSOC student that doesn't have access to hardware. This could help with contributions.
- All developers using the same tools. Could fix @stevegtaylor debugging problems and future people with windows

**Possible Drawbacks**

- Vulnerability from running untrusted code on devices.
- Issues with CubeMX generated code not conforming to static code analysis standards.
- Complexity in setup

**Additional Context**
Platformio remote development guide: https://docs.platformio.org/en/latest/plus/pio-remote.html
Platformio remote test command: https://docs.platformio.org/en/latest/core/userguide/remote/cmd_test.html
Setup of unit tests with CI: https://docs.platformio.org/en/latest/integration/ci/github-actions.html

I didn't see a way that remote development integrates with the github actions. More information is needed for that.

@jmadden173 can complete github actions part. Would be helpful if someone can setup raspi remote dev env.

**TODO**

- [x] Configure linting for platformio with `cppcheck.py`
- [x] Configure linting for python
- [x] Configure unit tests for python
- [x] Setup remote unit tests with platformio

**Comment by jmadden173** [comment]
Look at fixing SDI-12 unit tests blocking when no sensor is connection.

**Comment by jmadden173** [comment]
For python, we should be able to copy the configs from the `Dirtviz` repo.

**Comment by jmadden173** [comment]
Still need to add unit tests
